package com.example.test.Activities;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;

import androidx.appcompat.app.AppCompatActivity;
import androidx.fragment.app.FragmentManager;
import androidx.fragment.app.FragmentTransaction;

import com.example.test.Entities.Angles;
import com.example.test.Entities.Diagnostic;
import com.example.test.Entities.DiagnosticHasAngles;
import com.example.test.Entities.UserIsDiagnosed;
import com.example.test.Fragments.DiagnosesFragment;
import com.example.test.R;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

public class MenuActivity extends AppCompatActivity implements View.OnClickListener{
    private Button cameraButton;
    private Button logOutButton;
    private Button exercisesButton;
    private Button progressButton;
    private Button tutorialButton;
    final FirebaseDatabase database = FirebaseDatabase.getInstance();


    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_menu);

        cameraButton = findViewById(R.id.btnCamera);
        cameraButton.setOnClickListener((View.OnClickListener) this);

        logOutButton = findViewById(R.id.btnLogOut);
        logOutButton.setOnClickListener(this);

        exercisesButton = findViewById(R.id.btnExercises);
        exercisesButton.setOnClickListener(this);

        progressButton = findViewById(R.id.btnProgress);
        progressButton.setOnClickListener(this);

        tutorialButton = findViewById(R.id.btnTutorial);
        tutorialButton.setOnClickListener(this);

    }


    @Override
    public void onClick(View v) {
        switch (v.getId()){
            case R.id.btnCamera:
                startActivity(new Intent(this, CameraActivity.class));
                break;
            case R.id.btnLogOut:
                FirebaseAuth.getInstance().signOut();
                startActivity(new Intent(this, LogInActivity.class));
                break;

            case R.id.btnExercises:
               // getSupportFragmentManager().beginTransaction().replace(R.id.fragment_container, new DiagnosesFragment()).commit();
                startActivity(new Intent(this, ExercisesActivity.class));
                //exercises();
                break;
            case R.id.btnProgress:
                startActivity(new Intent(this, ProgressActivity.class));
                break;
            case R.id.btnTutorial:
                startActivity(new Intent(this, TutorialActivity.class));
                break;
        }
    }

    public void exercises(){
        // CONSIDER MOMENTAN CA AICI AM FACUT POZA
/*
        String userId = FirebaseAuth.getInstance().getCurrentUser().getUid();

    //    Diagnostic diagnostic = new Diagnostic();
    //    diagnostic.setImagePath("imagepatttththhhFINAL");
    //    diagnostic.setDate(new Date(System.currentTimeMillis()));

    //    DatabaseReference refD = database.getReference("/Users/" + user);
    //    DatabaseReference diagnosesRef = refD.child("Diagnoses");

        // Generate a reference to a new location and add some data using push();
    //    DatabaseReference pushedPostRef = diagnosesRef.push();
        // Get the unique ID generated by a push()
    //    String postId = pushedPostRef.getKey();

    //    Angles angles = new Angles();
    //    angles.setKyphosis(8.888888888);

    //    Map<String, Object> diagnosticUpdates = new HashMap<>();
     //   diagnostic.setAngles(angles);
     //   diagnosticUpdates.put(postId, diagnostic);

    //    diagnosesRef.updateChildren(diagnosticUpdates);

        DatabaseReference anglesRef = database.getReference("Angles");
        DatabaseReference pushedAnglestRef = anglesRef.push();
        String anglesId = pushedAnglestRef.getKey();
        Angles angles1 = new Angles();
        angles1.setKyphosis(3.3333);



        FirebaseDatabase.getInstance().getReference("Angles")
                .child(anglesId)
                .setValue(angles1);

        DatabaseReference diagnosticRef = database.getReference("Diagnostic");
        DatabaseReference pushedDiagnosticRef = diagnosticRef.push();
        String diagnosticId = pushedDiagnosticRef.getKey();
        Diagnostic diagnostic = new Diagnostic();
        diagnostic.setImagePath("PATHH33");
        diagnostic.setDate(new Date(System.currentTimeMillis()));


        FirebaseDatabase.getInstance().getReference("Diagnostic")
                .child(diagnosticId)
                .setValue(diagnostic);


        DatabaseReference diagnosticAnglesRef = database.getReference("Diagnostic has Angles");
        DatabaseReference pushedDiagnosticAnglesRef = diagnosticAnglesRef.push();
        String diagnosticAnglesId = pushedDiagnosticAnglesRef.getKey();
        DiagnosticHasAngles diagnosticHasAngles = new DiagnosticHasAngles(anglesId, diagnosticId);


        FirebaseDatabase.getInstance().getReference("Diagnostic has Angles")
                .child(diagnosticAnglesId)
                .setValue(diagnosticHasAngles);


        DatabaseReference userDiagnosticRef = database.getReference("User is diagnosed");
        DatabaseReference pushedUserDiagnosticRef = userDiagnosticRef.push();
        String userDiagnosedUserId = pushedUserDiagnosticRef.getKey();
        UserIsDiagnosed userIsDiagnosed = new UserIsDiagnosed(userId, diagnosticId);



        Map<String, Object> userUpdates = new HashMap<>();
        userUpdates.put(userDiagnosedUserId, userId);
        pushedUserDiagnosticRef.updateChildren(userUpdates);

        DatabaseReference userDiagnosedDiagnosticRef = database.getReference("User is diagnosed" + userDiagnosedUserId);
        String userDiagnosedDiagnosticId = userDiagnosedDiagnosticRef.push().getKey();

        Map<String, Object> userDiagnosedDiagnosticUpdates = new HashMap<>();
        userDiagnosedDiagnosticUpdates.put(userDiagnosedDiagnosticId, diagnosticId);

       // userDiagnosedDiagnosticRef.updateChildren(userDiagnosedDiagnosticUpdates);
       // FirebaseDatabase.getInstance().getReference("User is diagnosed")
       //         .child(userDiagnosticId)
      //          .setValue(userIsDiagnosed);

*/
        startActivity(new Intent(this, ExercisesActivity.class));

    }
}
