package com.example.test.Activities;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;

import androidx.appcompat.app.AppCompatActivity;
import androidx.fragment.app.FragmentManager;
import androidx.fragment.app.FragmentTransaction;

import com.example.test.Entities.Angles;
import com.example.test.Entities.Diagnostic;
import com.example.test.Fragments.DiagnosesFragment;
import com.example.test.R;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

public class MenuActivity extends AppCompatActivity implements View.OnClickListener{
    private Button cameraButton;
    private Button logOutButton;
    private Button exercisesButton;
    final FirebaseDatabase database = FirebaseDatabase.getInstance();


    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_menu);

        cameraButton = findViewById(R.id.btnCamera);
        cameraButton.setOnClickListener((View.OnClickListener) this);

        logOutButton = findViewById(R.id.btnLogOut);
        logOutButton.setOnClickListener(this);

        exercisesButton = findViewById(R.id.btnExercises);
        exercisesButton.setOnClickListener(this);


    }


    @Override
    public void onClick(View v) {
        switch (v.getId()){
            case R.id.btnCamera:
                startActivity(new Intent(this, CameraActivity.class));
                break;
            case R.id.btnLogOut:
                FirebaseAuth.getInstance().signOut();
                startActivity(new Intent(this, LogInActivity.class));
                break;

            case R.id.btnExercises:
               // getSupportFragmentManager().beginTransaction().replace(R.id.fragment_container, new DiagnosesFragment()).commit();
                exercises();
                break;

        }
    }

    public void exercises(){
        // CONSIDER MOMENTAN CA AICI AM FACUT POZA

        String user = FirebaseAuth.getInstance().getCurrentUser().getUid();

        Diagnostic diagnostic = new Diagnostic();
        diagnostic.setImagePath("imagepatttththhhFINAL");
        diagnostic.setDate(new Date(System.currentTimeMillis()));

        DatabaseReference refD = database.getReference("/Users/" + user);
        DatabaseReference diagnosesRef = refD.child("Diagnoses");

        // Generate a reference to a new location and add some data using push();
        DatabaseReference pushedPostRef = diagnosesRef.push();
        // Get the unique ID generated by a push()
        String postId = pushedPostRef.getKey();

        Angles angles = new Angles();
        angles.setKyphosis(8.888888888);

        Map<String, Object> diagnosticUpdates = new HashMap<>();
        diagnostic.setAngles(angles);
        diagnosticUpdates.put(postId, diagnostic);

        diagnosesRef.updateChildren(diagnosticUpdates);

        startActivity(new Intent(this, ExercisesActivity.class));

    }
}
